"""Add short_question to Question

Revision ID: e40826f3321d
Revises: 142e4b879b63
Create Date: 2024-04-03 23:06:33.343723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40826f3321d'
down_revision = '142e4b879b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_question', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_question', schema=None) as batch_op:
        batch_op.drop_column('short_question')

    # ### end Alembic commands ###
